# Generated by Django 4.2.2 on 2023-06-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_vulnerability_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
